name: tc-fase4-clean-architecture

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '7.0.x'
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TechChallenge.sln

      - name: Build
        run: dotnet build TechChallenge.sln --no-restore

  unit-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TechChallenge.sln

      - name: Build
        run: dotnet build TechChallenge.sln --no-restore

      - name: UnitTest
        run: dotnet test tests/HelpDesk.ApiService.Application.UnitTests/HelpDesk.ApiService.Application.UnitTests.csproj --no-build --verbosity normal

  architecture-test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v4.0.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore TechChallenge.sln

      - name: Build
        run: dotnet build TechChallenge.sln --no-restore

      - name: ArchitectureTest
        run: dotnet test tests/HelpDesk.ApiService.ArchitectureTests/HelpDesk.ApiService.ArchitectureTests.csproj --no-build --verbosity normal

  integration-test:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout code
          uses: actions/checkout@v4.1.4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4.0.0
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}

        - uses: actions/cache@v4.0.2
          with:
            path: ${{ env.NUGET_PACKAGES }}
            key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            restore-keys: |
              ${{ runner.os }}-nuget-

        - name: Restore dependencies
          run: dotnet restore TechChallenge.sln

        - name: Build
          run: dotnet build TechChallenge.sln --no-restore

        - name: IntegrationTest
          run: dotnet test tests/HelpDesk.ApiService.Api.IntegrationTests/HelpDesk.ApiService.Api.IntegrationTests.csproj --no-build --verbosity normal
